In [1]:
# inbuilt module to create an array in python called array module

In [1]:
import array

In [2]:
array.array("I",[1,2,3,4,5])

array('I', [1, 2, 3, 4, 5])

In [3]:
a=array.array("I",[1,2,3,4,5])

In [4]:
print(a)

array('I', [1, 2, 3, 4, 5])


In [6]:
print(type(a))

<class 'array.array'>


In [7]:
a=array.array("I",[1,2,3,4,5,"krishna"])

TypeError: 'str' object cannot be interpreted as an integer

In [8]:
a=array.array("I",[1,2,3,4,5"10"])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2742404757.py, line 1)

In [9]:
# numpy module

In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [13]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [14]:
b=np.array([1,2,3,4,5])

In [15]:
print(b)

[1 2 3 4 5]


In [16]:
c=np.array([1,2,3,4,5,"krishna"])

In [17]:
print(c)

['1' '2' '3' '4' '5' 'krishna']


In [18]:
d=np.array([1,2,3,4,5,10.5])

In [19]:
print(d)

[ 1.   2.   3.   4.   5.  10.5]


In [21]:
e=np.array([1,2,3,4,5,"10"],dtype=np.int8)

In [22]:
print(e)

[ 1  2  3  4  5 10]


In [23]:
f=np.array([1,2,3,4,5,"10.5"])

In [24]:
print(f)

['1' '2' '3' '4' '5' '10.5']


In [25]:
f=np.array([1,2,3,4,5,"10.5"],dtype=np.float16)

In [26]:
print(f)

[ 1.   2.   3.   4.   5.  10.5]


In [27]:
np.array(f,dtype=np.int8)

array([ 1,  2,  3,  4,  5, 10], dtype=int8)