In [1]:
# loops

# What is loops

In [2]:
# while loop

# for loop

# Do while loop

In [3]:
for i in "krishna":
    print(i)

k
r
i
s
h
n
a


In [9]:
a="krishna"
i=0
while i<len(a):
    print(a,[i])
    i+=1

krishna [0]
krishna [1]
krishna [2]
krishna [3]
krishna [4]
krishna [5]
krishna [6]


In [11]:
# initializer
# while condition:
#       statements(s)
#       increment/decrement

In [14]:
i=0
while i<10:
    print("hello world")
    i+=1

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world


In [15]:
i=0
while i<10:
    print(i,"hello world")
    i+=1

0 hello world
1 hello world
2 hello world
3 hello world
4 hello world
5 hello world
6 hello world
7 hello world
8 hello world
9 hello world


In [17]:
i=0
while i<10:
    print(i+1,"hello world")
    i+=1

1 hello world
2 hello world
3 hello world
4 hello world
5 hello world
6 hello world
7 hello world
8 hello world
9 hello world
10 hello world


In [18]:
i=1
while i<11:
    print(i,"hello world")
    i+=1

1 hello world
2 hello world
3 hello world
4 hello world
5 hello world
6 hello world
7 hello world
8 hello world
9 hello world
10 hello world


In [20]:
# iterator: for loop and while loop (__iter__(),__next__())
# iterable: __iter__()
# iteration:

In [22]:
# while loop
# break
# continue
# else
# pass
# nested while loop
# single while loop pattern
# multi while loop pattern

In [23]:
i=0
while i<10:
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9


In [27]:
i=0
while i<10:
    if i==4:
        i=i+1
        continue
    print(i)
    i=i+1

0
1
2
3
5
6
7
8
9


In [28]:
i=0
while i<10:
    if i==4:
        i=i+1
        break
    print(i)
    i=i+1

0
1
2
3


In [29]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        break
    print(i)
    i=i+1

0
1
2
3
i am manish


In [30]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        i+=1
        break
    print(i)
    i=i+1

0
1
2
3
i am manish


In [31]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        i+=1
        continue
    print(i)
    i=i+1

0
1
2
3
i am manish
5
6
7
8
9


In [32]:
i=0
while i<10:
    if i==4 or i==6:
        print("i am manish")
        i+=1
        continue
    print(i)
    i=i+1

0
1
2
3
i am manish
5
i am manish
7
8
9


In [34]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        i+=1
    if i==6:
        print("i am student")
        i+=1
    if i==9:
        print("i am a engineer")
        i+=1
        continue
    print(i)
    i=i+1

0
1
2
3
i am manish
5
i am student
7
8
i am a engineer


In [35]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        i+=1
    if i==6:
        print("i am student")
        i+=1
    if i==9:
        print("i am a engineer")
        i+=1
        continue
    print(i+1)
    i=i+1

1
2
3
4
i am manish
6
i am student
8
9
i am a engineer


In [36]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        i+=1
    if i==6:
        print("i am student")
        i+=1
    if i==9:
        print("i am a engineer")
        i+=1
        continue
    print(i)
    i=i+1
else:
    print("good bye")

0
1
2
3
i am manish
5
i am student
7
8
i am a engineer
good bye


In [37]:
i=0
while i<10:
    if i==4:
        print("i am manish")
        i+=1
    if i==6:
        print("i am student")
        i+=1
        break
    if i==9:
        print("i am a engineer")
        i+=1
        continue
    print(i)
    i=i+1
else:
    print("good bye")

0
1
2
3
i am manish
5
i am student


In [45]:
# for loop
# break
# continue
# else
# pass
# nested for loop
# single for loop pattern
# multi for loop pattern
# list comprehension
# dictionary comprehension
# set comprehension

In [39]:
a=[1,2,3,4,5,6,7,8,9]
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9


In [40]:
a=[1,2,3,4,5,6,7,8,9]
for i in a:
    if i==4 or i==6:
        continue
    print(i)

1
2
3
5
7
8
9


In [41]:
a=[1,2,3,4,5,6,7,8,9]
for i in a:
    if i==4 or i==6:
        break
    print(i)

1
2
3


In [42]:
a=[1,2,3,4,5,6,7,8,9]
for i in a:
    if i==4 or i==6:
        print("loop is breaked now")
        break
    print(i)

1
2
3
loop is breaked now


In [43]:
a=[1,2,3,4,5,6,7,8,9]
for i in a:
    if i==4 or i==6:
        print("loop is breaked now")
        continue
    print(i)

1
2
3
loop is breaked now
5
loop is breaked now
7
8
9


In [44]:
a=[1,2,3,4,5,6,7,8,9]
for i in a:
    if i==4 or i==6:
        print("loop is breaked now")
        continue
    print(i)
else:
    print("good bye")

1
2
3
loop is breaked now
5
loop is breaked now
7
8
9
good bye


In [46]:
# neated loop

In [47]:
# *
# **
# ***
# ****
# *****

In [48]:
print("*"*1)
print("*"*1)
print("*"*1)
print("*"*1)
print("*"*1)

*
*
*
*
*


In [49]:
print("*"*1)
print("*"*2)
print("*"*3)
print("*"*4)
print("*"*5)

*
**
***
****
*****


In [50]:
"krishna"*5

'krishnakrishnakrishnakrishnakrishna'

In [52]:
for i in range(1,6):
    print("*"*i)

*
**
***
****
*****


In [53]:
for i in range(1,6):
    print(i,"*"*i)

1 *
2 **
3 ***
4 ****
5 *****


In [54]:
range(10)

range(0, 10)

In [55]:
dir(a)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [56]:
import sys

In [58]:
a=range(10)

In [59]:
a

range(0, 10)

In [60]:
sys.getsizeof(a)

48

In [61]:
b=[0,1,2,3,4,5,6,7,8,9]

In [62]:
sys.getsizeof(b)

136

In [63]:
c=range(0,10000)

In [64]:
c

range(0, 10000)

In [65]:
sys.getsizeof(c)

48

In [66]:
cont=[i for i in range(0,1000)]

In [67]:
print(cont)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [68]:
sys.getsizeof(cont)

8856

In [69]:
range(1,10,1)

range(1, 10)

In [71]:
e=range(1,10,2)

In [73]:
print(sys.getsizeof(e))

48


In [75]:
import numpy as np

In [76]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [78]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
d=range(1,10,2)
for i in d:
    print(i)

1
3
5
7
9


In [81]:
d=range(10,1,-2)
for i in d:
    print(i)

10
8
6
4
2


In [83]:
for i in range(5):
    for j in range(i):
        print("*",end="")
    print()


*
**
***
****


In [84]:
for i in range(5):
    for j in range(i+1):
        print("*",end="")
    print()

*
**
***
****
*****


In [1]:
i=0
while i<5:
    j=0
    while j<i+1:
        print("*",end=" ")
        j+=1
    print()
    i+=1

* 
* * 
* * * 
* * * * 
* * * * * 
