In [1]:
a=[10,10.0,"string"]

In [2]:
print(a)

[10, 10.0, 'string']


In [16]:
# List constructor is list()
# List literal is[]
# List is a set of elements
# List is mutable
# List support indexing and slicing
# List support concatination
# It has multiple methods 

In [17]:
a= list()
print(a)
print(type(a))

[]
<class 'list'>


In [18]:
bool(list())

False

In [19]:
bool(list(""))

False

In [20]:
a=[""]
bool(a)

True

In [21]:
c=[]
print(type(c))
print(c)

<class 'list'>
[]


In [32]:
a=["krishna","kumar","mohit",10,20,10.0]

In [33]:
a[0]

'krishna'

In [34]:
print(a[0])

krishna


In [35]:
a[2]

'mohit'

In [36]:
a[-3]

10

In [38]:
a[1:3]

['kumar', 'mohit']

In [39]:
a[::2]

['krishna', 'mohit', 20]

In [40]:
a[0:5+1]

['krishna', 'kumar', 'mohit', 10, 20, 10.0]

In [41]:
a[1::2]

['kumar', 10, 10.0]

In [42]:
a[-1::-2]

[10.0, 10, 'kumar']

In [43]:
a[::-2]

[10.0, 10, 'kumar']

In [44]:
a[-1:-6:-2]

[10.0, 10, 'kumar']

In [47]:
print(a)
print(id(a))

['krishna', 'kumar', 'mohit', 10, 20, 10.0]
1860144468928


In [48]:
b=["krishna"]
print(b)
print(id(b))

['krishna']
1860144846528


In [49]:
c=a+b
print(c,id(c))

['krishna', 'kumar', 'mohit', 10, 20, 10.0, 'krishna'] 1860144528512


In [50]:
dir([])

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [57]:
a=[10,20,3,4,5,6]
print(id(a))

1860144845248


In [58]:
a.append(10)

In [59]:
print(a)
print(id(a))

[10, 20, 3, 4, 5, 6, 10]
1860144845248


In [62]:
a=tuple()
for i in range(10):
    a=a+(i,)
    print(a)
    print(id(a))

(0,)
1860144422512
(0, 1)
1860150293632
(0, 1, 2)
1860144524480
(0, 1, 2, 3)
1860150194112
(0, 1, 2, 3, 4)
1860150189872
(0, 1, 2, 3, 4, 5)
1860146101504
(0, 1, 2, 3, 4, 5, 6)
1860146101984
(0, 1, 2, 3, 4, 5, 6, 7)
1860146251456
(0, 1, 2, 3, 4, 5, 6, 7, 8)
1860146251200
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
1860146254400


In [65]:
a=list()
for i in range(10):
    b.append(i)
    print(b)
    print(id(b))

['krishna', 0]
1860144846528
['krishna', 0, 1]
1860144846528
['krishna', 0, 1, 2]
1860144846528
['krishna', 0, 1, 2, 3]
1860144846528
['krishna', 0, 1, 2, 3, 4]
1860144846528
['krishna', 0, 1, 2, 3, 4, 5]
1860144846528
['krishna', 0, 1, 2, 3, 4, 5, 6]
1860144846528
['krishna', 0, 1, 2, 3, 4, 5, 6, 7]
1860144846528
['krishna', 0, 1, 2, 3, 4, 5, 6, 7, 8]
1860144846528
['krishna', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1860144846528


In [67]:
b=[i for i in range(10)]

In [ ]:
#array: a collection which contain similar datatype is called array.

In [68]:
a=[1,2,3,4,5,6,7,8,9,0]

In [69]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [70]:
type(a)

list

In [71]:
import array

In [73]:
array.array("I",[1,2,3,4,5,6,7,8,9,0])

array('I', [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [74]:
b=array.array("I",[1,2,3,4,5,6,7,8,9,0])

In [75]:
print(b)

array('I', [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])


In [76]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [77]:
print(type(a))

<class 'list'>


In [78]:
array.array("I",[1,2,3,4,5,6,7,8,9,0,"krishan"])

TypeError: 'str' object cannot be interpreted as an integer

In [80]:
print(type(a))

<class 'list'>


In [81]:
id(a[0])

140728220771112

In [83]:
c=[id(a[0]),id(a[1]),id(a[2]),id(a[3]),id(a[4]),id(a[5]),id(a[6]),id(a[7]),id(a[8]),id(a[9])]

In [84]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [85]:
print(c)

[140728220771112, 140728220771144, 140728220771176, 140728220771208, 140728220771240, 140728220771272, 140728220771304, 140728220771336, 140728220771368, 140728220771080]


In [86]:
b

array('I', [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [87]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 6.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [88]:
import numpy as np

In [89]:
np.array([1,2,3,4,5,6,7,8,9,])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
d=np.array([1,2,3,4,5,6,7,8,9,])

In [91]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
print(d)

[1 2 3 4 5 6 7 8 9]


In [93]:
d=np.array([1,2,3,4,5,6,7,8,9,"krishna"])

In [94]:
print(d)

['1' '2' '3' '4' '5' '6' '7' '8' '9' 'krishna']


In [95]:
d=np.array([1,2,3,4,5,6,7,8,9,"krishna"],dtype=np.int16)

ValueError: invalid literal for int() with base 10: 'krishna'

In [96]:
d=np.array([1,2,3,4,5,6,7,8,9,"10"],dtype=np.int16)

In [97]:
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


In [98]:
# list is not an array
# to create array in python we use either numpy package( third party package) or python array module

In [99]:
# Nesting

In [104]:
g=[1,2,3,4,[5,6,7,"krishna",8]]

In [105]:
g

[1, 2, 3, 4, [5, 6, 7, 'krishna', 8]]

In [106]:
g[1]

2

In [109]:
g[4][3][5]

'n'

In [112]:
h=g[4]
print(h)

[5, 6, 7, 'krishna', 8]


In [114]:
i=h[3]
print(i)

krishna


In [116]:
j=i[5]
print(j)

n


In [119]:
g[4][3][5]

'n'

In [120]:
j=[]
j.append(1)


In [121]:
print(j)

[1]


In [122]:
j.append(10.0)

In [123]:
print(j)

[1, 10.0]


In [124]:
j.append("krishna")

In [125]:
print(j)

[1, 10.0, 'krishna']


In [126]:
j.append([1,2,3,4,5])

In [127]:
print(j)

[1, 10.0, 'krishna', [1, 2, 3, 4, 5]]


In [128]:
j.append(1,10)

TypeError: list.append() takes exactly one argument (2 given)

In [129]:
j.extend("krishna")

In [130]:
print(j)

[1, 10.0, 'krishna', [1, 2, 3, 4, 5], 'k', 'r', 'i', 's', 'h', 'n', 'a']


In [131]:
j.extend([1,2,3,4])

In [132]:
print(j)

[1, 10.0, 'krishna', [1, 2, 3, 4, 5], 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 3, 4]


In [137]:
j.extend(["krishna"])

In [138]:
print(j)

[1, 10.0, 'krishna', [1, 2, 3, 4, 5], 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 3, 4, 'krishna', 'krishna', 'krishna']


In [139]:
j.index("krishna")

2

In [140]:
j.index(3)

13

In [141]:
j.index([1,2,3,4,5])

3

In [143]:
j.index(3)

13

In [146]:
j.remove("krishna")

In [147]:
print(j)

[1, 10.0, [1, 2, 3, 4, 5], 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 3, 4, 'krishna', 'krishna']


In [148]:
j.remove(3)

In [149]:
print(j)

[1, 10.0, [1, 2, 3, 4, 5], 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna']


In [150]:
j.remove([1,2,3,4,5])

In [151]:
print(j)

[1, 10.0, 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna']


In [152]:
j.count(1)

2

In [153]:
j.count("krishna")

2

In [154]:
j.count("k")

1

In [156]:
j.insert(2,"krishna")

In [157]:
print(j)

[1, 10.0, 'krishna', 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna']


In [158]:
j.append([1,2,3,4,5])

In [159]:
print(j)

[1, 10.0, 'krishna', 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna', [1, 2, 3, 4, 5]]


In [161]:
j[15]

[1, 2, 3, 4, 5]

In [162]:
h=j[15]
print(h)

[1, 2, 3, 4, 5]


In [163]:
h.insert(2,"krishna")

In [164]:
print(h)

[1, 2, 'krishna', 3, 4, 5]


In [172]:
print(j)

[1, 10.0, 'krishna', 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna', [1, 2, 'krishna', 3, 4, 5]]


In [174]:
a=[1, 10.0, 'krishna', 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna', [1, 2, 'krishna', 3, 4, 5]]

In [175]:
cont=[]
for i in a:

    if type(i)==list:
        for j in i:
            cont.append(j)
        continue
    cont.append(i)
print(cont)

[1, 10.0, 'krishna', 'k', 'r', 'i', 's', 'h', 'n', 'a', 1, 2, 4, 'krishna', 'krishna', 1, 2, 'krishna', 3, 4, 5]


In [3]:
b=[]

In [4]:
b.append(10)
print(b)

[10]


In [5]:
b.append(10.0)

In [6]:
print(b)

[10, 10.0]


In [7]:
b.append("manish")

In [8]:
print(b)

[10, 10.0, 'manish']


In [9]:
b.append([1,2,3,4])

In [10]:
print(b)

[10, 10.0, 'manish', [1, 2, 3, 4]]


In [11]:
b.append(bool(1))

In [12]:
print(b)

[10, 10.0, 'manish', [1, 2, 3, 4], True]


In [13]:
b.count("manish")

1

In [14]:
b.index("manish")

2

In [15]:
b.insert(1,"rohan")

In [16]:
print(b)

[10, 'rohan', 10.0, 'manish', [1, 2, 3, 4], True]


In [17]:
b[4]

[1, 2, 3, 4]

In [18]:
a=b[4]

In [19]:
print(a)

[1, 2, 3, 4]


In [20]:
a.insert(2,"krishna")

In [21]:
print(a)

[1, 2, 'krishna', 3, 4]


In [22]:
print(b)

[10, 'rohan', 10.0, 'manish', [1, 2, 'krishna', 3, 4], True]


In [23]:
b[4],
b.insert(3,"kumar")

In [24]:
print(b)

[10, 'rohan', 10.0, 'kumar', 'manish', [1, 2, 'krishna', 3, 4], True]


In [25]:
b.pop()

True

In [26]:
print(b)

[10, 'rohan', 10.0, 'kumar', 'manish', [1, 2, 'krishna', 3, 4]]


In [27]:
b.pop()

[1, 2, 'krishna', 3, 4]

In [28]:
print(b)

[10, 'rohan', 10.0, 'kumar', 'manish']


In [29]:
b.remove("manish")

In [30]:
print(b)

[10, 'rohan', 10.0, 'kumar']


In [31]:
b.remove("rohan")

In [32]:
print(b)

[10, 10.0, 'kumar']


In [33]:
b.reverse()

In [34]:
print(b)

['kumar', 10.0, 10]


In [35]:
b.reverse()

In [36]:
print(b)

[10, 10.0, 'kumar']


In [37]:
b.append([1,2,3,4])

In [38]:
print(b)

[10, 10.0, 'kumar', [1, 2, 3, 4]]


In [39]:
b[3].reverse()

In [40]:
print(b)

[10, 10.0, 'kumar', [4, 3, 2, 1]]


In [41]:
b[3].reverse()

In [42]:
print(b)

[10, 10.0, 'kumar', [1, 2, 3, 4]]


In [43]:
c=[[i] for i in range(10)]

In [44]:
print(c)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]


In [45]:
c.reverse()

In [46]:
print(c)

[[9], [8], [7], [6], [5], [4], [3], [2], [1], [0]]


In [47]:
c.sort()

In [48]:
print(c)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]


In [49]:
c.clear()

In [50]:
print(c)

[]


In [51]:
c.extend([1,2,3,4,5])

In [52]:
print(c)

[1, 2, 3, 4, 5]


In [53]:
c.append([1,2,3,4,5])

In [54]:
print(c)

[1, 2, 3, 4, 5, [1, 2, 3, 4, 5]]


In [57]:
# extend, append, insert

In [58]:
c=[]
c.extend([1,2,3,4,5])        # iterable
print(c)

[1, 2, 3, 4, 5]


In [59]:
c.append([1,2,3,4,5])

In [60]:
print(c)

[1, 2, 3, 4, 5, [1, 2, 3, 4, 5]]


In [61]:
c.insert(3,[1,2,3,4])

In [62]:
print(c)

[1, 2, 3, [1, 2, 3, 4], 4, 5, [1, 2, 3, 4, 5]]


In [63]:
c[3]

[1, 2, 3, 4]

In [64]:
d=c[3]

In [65]:
d.insert(2,"keishna")

In [66]:
print(d)

[1, 2, 'keishna', 3, 4]


In [67]:
print(c)

[1, 2, 3, [1, 2, 'keishna', 3, 4], 4, 5, [1, 2, 3, 4, 5]]


In [68]:
print(c)

[1, 2, 3, [1, 2, 'keishna', 3, 4], 4, 5, [1, 2, 3, 4, 5]]


In [75]:
b=c.copy()

In [76]:
id(b),id(c)

(2650451356352, 2650457730816)